document.body.style.margin = '0';
document.body.style.height = '100vh';
document.body.style.display = 'flex';
document.body.style.alignItems = 'center';
document.body.style.justifyContent = 'center';
document.body.style.background = '#fff0f5';
document.body.style.fontFamily = 'Arial, sans-serif';
document.body.style.fontSize = '2em';
document.body.style.color = '#ff3366';
